// <auto-generated />
namespace CodeCat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Forgottoremoveoneicollectable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Forgottoremoveoneicollectable));
        
        string IMigrationMetadata.Id
        {
            get { return "201705071649047_Forgot to remove one icollectable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
